version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña_root
      MYSQL_DATABASE: nombre_de_la_base_de_datos
      MYSQL_USER: tu_usuario
      MYSQL_PASSWORD: tu_contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

